# Generated by Django 5.0.1 on 2024-06-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_newsletter_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_code_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
