services:
  - type: web
    name: api
    env: docker
    buildCommand: |
      docker build -t $DOCKER_IMAGE_NAME -f back-end/Dockerfile .
    plan: starter
    # Add additional settings like environment variables, ports, and scaling as needed

  - type: web
    name: web
    env: docker
    buildCommand: |
      docker build -t $DOCKER_IMAGE_NAME -f front-end/Dockerfile .
    plan: starter
