# Generated by Django 5.0.1 on 2024-04-01 04:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_alter_cartitem_created_by_and_more"),
        ("items", "0008_alter_note_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoriteitem",
            unique_together={("created_by", "item")},
        ),
    ]
