# Generated by Django 5.0.1 on 2024-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0003_alter_newsletter_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
