# Generated by Django 5.0.1 on 2024-02-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_modify_item_model_add_brand_and_stockItem_models"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="stock_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.stockitem"
            ),
        ),
    ]
