# Generated by Django 5.0.1 on 2024-01-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="reviews",
        ),
        migrations.AddField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="items.item",
            ),
            preserve_default=False,
        ),
    ]
