# Generated by Django 5.0.1 on 2024-01-26 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_remove_item_reviews_review_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("item", "created_by"), name="unique_user_item_review"
            ),
        ),
    ]
