# Generated by Django 5.0.1 on 2024-03-07 10:47

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_modify_item_model_add_brand_and_stockItem_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo_img",
            field=models.ImageField(upload_to=items.models.get_image_file_path),
        ),
    ]
