# Generated by Django 5.0.1 on 2024-03-29 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_alter_brand_created_by_alter_item_created_by_and_more"),
        ("items", "0006_remove_item_tags_note_notecategory"),
    ]

    operations = []
