# Generated by Django 5.0.1 on 2024-03-07 10:47

import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="html_file",
            field=models.FileField(
                blank=True, null=True, upload_to=newsletter.models.get_file_path
            ),
        ),
    ]
