import type { Metadata } from 'next';
import { Montserrat } from "next/font/google";
import Head from 'next/head';
import { App } from '@/app/components/App';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PerfuMe",
  description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="./favicon.png" />
      </Head>

      <body className={montserrat.className}>
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}
